### ISSUE TITLE
How to use the web api (active model serializers) ?

### ISSUE THREAD

**Issue by toranb** [aarongray/northwind-rails#1]
I'm not a ruby/rails developer but ... I'd love to use this exact project to learn how active model serializes work for some ember hacking :)

I'm working on a series showing "ember in the wild" and I'd love a backend that just works (and has a one-to-many / many-to-many relationship working out of the box). Any plans to make this http friendly using something like active model serializes?

And if you do ... what would the json look like (for this app) to expose a many-to-many relationship? What can I do to help ship the http/api version of this?

Thanks for pushing up a great project for rails newbs like myself :)

**Comment by aarongray** [comment]
Howdy! Thanks for stopping by and for the kind words. That is neat you're working with Ember.

Cool idea about adding ActiveModel Serializers. I did end up making a demo front end that works with this back end, which you can check out here: https://github.com/aarongray/northwind-angular. It uses Angular, and I have not added front end functionality for every model, but what is there is functional, and you may find it a helpful comparison nonetheless.

There are a couple different branches on each project that demonstrate different things. If you use both master branches, it would be a vanilla Angular app with a vanilla Rails backend as the API. Or, you could use the grape branch on this project, which uses Grape to serve up the API that is consumed by the Angular app.

I'm busy working on a new venture right now, so I don't have time to add ActiveModel Serializers, but if you'd like to add it on a new branch, that would be rad!

**Comment by toranb** [comment]
Awesome! I'll take a look at the Angular branch and see if it's close enough for what I'm planning to hack around on :)

**Comment by aarongray** [comment]
Cool. Potential gotcha: I don't think the `angular-on-rails` branch of this project is what you want. I think it is an unfinished WIP branch.

I'd recommend doing what I mentioned above - use the master branch of both `northwind-rails` and `northwind-angular` repos.
